fix: use dynamic IDs in migrations (#245)
Fixes several previous migrations relying on non-existent hardcoded IDs
when creating a new project.
Updating previous migrations is not supposed to happen, however, no
migration logic is changed.
It now relies on the API to find the right IDs using the corresponding
label.

## How to reproduce
1. Follow "Getting started guide" from `main` on a personal DatoCMS
account
1. Upon running `npx datocms migrations:run --destination=start
--fast-fork` at the corresponding step, expect an error

Example of a related error 
(saved during debugging, this is not the first error to show up, but
they are all similar)
```bash
Running migration "1730405111_linkRecords.ts"... failed!

----
Error: PUT https://site-api.datocms.com/item-types/EkWwcYfPQSGXskAZKO_tTg: 404 Not Found

[
  {
    "id": "302048",
    "type": "api_error",
    "attributes": {
      "code": "NOT_FOUND",
      "details": {}
    }
  }
]
```

I inferred the itemTypes for `page` and `home_page` from inspecting an
existing DatoCMS instance that uses Head Start, please check if this is
correct.

# Changes
- Updates references to non existent IDs with API calls to find the
correct ID in a new instance
- Adds error handling for finding `menuItems` since it now relies on
finding IDs in a list

# How to test

1. Remove the start environment if it was created when attempting to
reproduce the error
1. __If testing without reproducing, simply follow getting started
guide__
1. Run `npx datocms migrations:run --destination=start --fast-fork`
1. Migrations should succeed

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have made sure that my PR is easy to review (not too big,
includes comments)
- [x] I have made updated relevant documentation files (in project
README, docs/, etc)
- [x] I have added a decision log entry if the change affects the
architecture or changes a significant technology
- [x] I have notified a reviewer

<!-- Please strike through and check off all items that do not apply
(rather than removing them) -->

Co-authored-by: Jasper Moelker <jasper@voorhoede.nl>